### ISSUE TITLE
Add consts for supported types

### ISSUE THREAD

**Issue by amirrezaask** [golobby/cast#1]
Add constants for supported types something like
```go
const Uint8 = "uint8"

// in user code
val, err := cast.FromString("666", cast.Uint8)
```
this will help our users to avoid typos and also increases the discoverability of our library features and supported types since we can rely on auto-complete features from editors and IDEs.

**Comment by amirrezaask** [comment]
I will add this if @miladrahimi you are OK

**Comment by miladrahimi** [comment]
It's OK, thanks buddy.

**Comment by amirrezaask** [comment]
This will resolve this issue https://github.com/golobby/cast/pull/2
